### PR TITLE
Bala materials

### PR DESCRIPTION
**Pull request by dmbala**
Day4/OSG Connect exercises: host and flock names corrected

### CODE REVIEW

**Comment by brianhlin** [comment]
This looks good but could you also remove all the `<strong>...</strong>` tags?

**Comment by dmbala** [comment]
Thanks Brian, good catch, will do.

**Comment by dmbala** [comment]
Hi Brian, All

Looks like all the exercises in the other days also use <strong> .. 
</strong> tag.  Not sure if this is the style we should keep or change.

Bala

**Comment by brianhlin** [comment]
That's because the other exercises haven't been fixed yet :). If you preview your changes, you'll see that the strong tags show up verbatim in the console blocks, which is definitely what we don't want.

**Comment by dmbala** [comment]
ah, okay. thanks for the clarifications.  i will go ahead and make the 
changes for my session.

cheers

Bala

**Comment by dmbala** [comment]
someone need to approve my pull request so that I can make a new request

**Pull request merged**
