### PR TITLE
Touch up the detailed schedule

### PR DESCRIPTION
**Pull request by brianhlin**
Using markdown tables for the actual schedule will make it easier to edit in the future.

### CODE REVIEW

**Comment by lmichael107** [comment]
Thank you! 'Was going to tackle this today - just wanted to get the
schedule up ASAP.

-Lauren

Lauren Michael - Research Computing Facilitator, Center for High Throughput
Computing <http://chtc.cs.wisc.edu/>, University of Wisconsin - Madison
Other Affiliations: Advanced Computing Initiative
<http://aci.wisc.edu/>; Wisconsin
Institute for Discovery <http://wid.wisc.edu/profile/lauren-michael/>;
ACI-REF <http://aci-ref.org/>
lmichael@wisc.edu, www.tinyurl.com/LMichaelCalendar, Discovery 2262,
(608)316-4430

**Comment by osg-cat** [comment]
I am not happy with this change at all. It loses all ability to format individual rows with CSS classes, which the old (TWiki) version had.

**Comment by brianhlin** [comment]
What different classes of rows do you want to differentiate between? I'm sure we can handle it without needing to have raw HTML in the contents

**Comment by osg-cat** [comment]
Please look at the original HTML. I understand that the MD-converted version does not show the colors when rendered, because the CSS got stripped out. But the classes are all there in the HTML.

**Comment by brianhlin** [comment]
Yea, I see that. I was suggesting that we find another way to differentiate between the different types of "Events" that is better supported in the MkDocs ecosystem instead of having to maintain HTML/CSS.

**Comment by osg-cat** [comment]
And what is your proposal? Markdown is so underpowered that nothing came to mind immediately. I am *not* in favor of a %X% hack like you did elsewhere. That’s just inventing yet another language, effectively.

**Comment by brianhlin** [comment]
That goes back to my original question: what different classes of rows do you want to differentiate between? The classes I see are meal, time, break, and "inst". And also, why? We can highlight meals/breaks with a simple solution like bolding them; I'm not sure what an "inst" is; and what's the point of having a class for times? 

I'd gladly give up the fine-grained control of making single cells in a table look a certain way so that instructors can easily edit the detailed schedule. A mess of HTML and CSS for a very minor feature strikes me as the antithesis to "don't make me think".

**Comment by osg-cat** [comment]
I am done with this thread. I believe the original table was more user-friendly than the Markdown one. I do not care whether the source code is DMMT — we are technology professionals and my expectation is that anyone in the group should be able to handle something as easy as HTML and some very lightweight CSS. But I don’t have the time to convince you of the usefulness of clear formatting for users.

**Pull request merged**
